stages:
  - build
  - deploy
insight_build:
  stage: build
  image: docker:latest
  script:
    - cd scripts/Docker
    - docker build --build-arg INSIGHT_BRANCH=$CI_COMMIT_REF_NAME --build-arg INSIGHT_REPO=$INSIGHT_REPO -t "$IMAGE_URL:$CI_COMMIT_REF_NAME" .
insight_deploy:
  stage: deploy
  script:
    - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USERNAME" --password-stdin "$REGISTRY_DOMAIN"
    - docker push "$IMAGE_URL:$CI_COMMIT_REF_NAME"
