group: travis
dist: bionic
language: python
services:
  - docker
python:
  - "3.11"
install:
  - docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli:latest generate -i "https://esi.evetech.net/latest/swagger.json" -l python -o /local/swagger-python-client
  - sudo chown -R $USER swagger-python-client
  - cd swagger-python-client
  - python3 setup.py install
  - cd ..
  - rm swagger-python-client -R
  - pip install -r requirements.txt
  - pip install codecov
script:
  - pytest
after_success:
  - codecov
